/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.PharmacistForm;

import ComponentGUI.DetailCard;
import ComponentGUI.Table;
import Controller.DeleteObatController;
import Controller.RefreshObatController;
import Controller.TambahObatController;
import Model.Obat;
import Utility.Database;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ManageObatForm extends javax.swing.JPanel {

    private DetailCard detailCard;
    private String namaObat = "";

    public ManageObatForm() {
        initComponents();
        TableScrollPanel.getVerticalScrollBar().setBackground(Color.WHITE);
        TableScrollPanel.getViewport().setBackground(Color.WHITE);
        detailCard = new DetailCard();

        // Refresh controller 
        RefreshObatController refresh = new RefreshObatController(TableObat);
        refreshButton.addActionListener(refresh);

        // Delete controller 
        deleteButton.addActionListener(evt -> handleDelete());
        editButton.addActionListener(evt -> handleEdit());

        TableObat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = TableObat.getSelectedRow();
                if (selectedRow != -1) {
                    namaObat = TableObat.getValueAt(selectedRow, 0).toString();
                    tampilkanDetailObat(namaObat);
                }
            }
        });

        // Edit controller
    }

    private void handleEdit() {
        TableObat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = TableObat.getSelectedRow();
                if (selectedRow != -1) {
                    namaObat = TableObat.getValueAt(selectedRow, 0).toString();
                }
            }
        });
        if (!namaObat.isEmpty()) {
            DialogEdit dialogEdit = new DialogEdit(namaObat);
            dialogEdit.setSize(400, 300);
            dialogEdit.setVisible(true);
            namaObat = "";
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih obat yang ingin dihapus");
        }
    }

    private void handleDelete() {
        TableObat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = TableObat.getSelectedRow();
                if (selectedRow != -1) {
                    namaObat = TableObat.getValueAt(selectedRow, 0).toString();
                }
            }
        });
        if (!namaObat.isEmpty()) {
            DeleteObatController delete = new DeleteObatController(namaObat, TableObat);
            delete.actionPerformed(null);
            namaObat = "";
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih obat yang ingin dihapus");
        }

    }

    public String getNamaObat() {
        return namaObat;
    }

    public void setNamaObat(String namaObat) {
        this.namaObat = namaObat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        PanelSearch = new GUI.PanelBorder();
        PanelDaftarObat = new GUI.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        TableScrollPanel = new javax.swing.JScrollPane();
        TableObat = new ComponentGUI.Table();
        refreshButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        panelBorder1 = new GUI.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelAturanPakai = new javax.swing.JLabel();
        labelPetunjukPenyimpnan = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dosisLB = new javax.swing.JLabel();
        kegunaanLB = new javax.swing.JLabel();
        komposisiLB = new javax.swing.JLabel();
        obatLB = new javax.swing.JLabel();
        kadaluarsaLB = new javax.swing.JLabel();
        LabelDosis = new javax.swing.JLabel();
        aturanPakaiLB = new javax.swing.JLabel();
        labelKegunaan = new javax.swing.JLabel();
        penyimpananLB = new javax.swing.JLabel();
        labelKomposisi = new javax.swing.JLabel();
        labelNoRegistrasi = new javax.swing.JLabel();
        noRegistrasiLB = new javax.swing.JLabel();
        hargaLB = new javax.swing.JLabel();
        labelKadaluarsa = new javax.swing.JLabel();
        stokLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(984, 0));

        PanelSearch.setForeground(new java.awt.Color(76, 184, 196));

        javax.swing.GroupLayout PanelSearchLayout = new javax.swing.GroupLayout(PanelSearch);
        PanelSearch.setLayout(PanelSearchLayout);
        PanelSearchLayout.setHorizontalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSearchLayout.setVerticalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        PanelDaftarObat.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Daftar Obat");

        TableScrollPanel.setBorder(null);

        TableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "No Registrasi", "Stok", "Harga"
            }
        ));
        TableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableObatMouseClicked(evt);
            }
        });
        TableScrollPanel.setViewportView(TableObat);

        refreshButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.setBorder(null);
        refreshButton.setBorderPainted(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit");
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setBorder(null);
        deleteButton.setBorderPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDaftarObatLayout = new javax.swing.GroupLayout(PanelDaftarObat);
        PanelDaftarObat.setLayout(PanelDaftarObatLayout);
        PanelDaftarObatLayout.setHorizontalGroup(
            PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDaftarObatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDaftarObatLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TableScrollPanel))
                .addGap(20, 20, 20))
        );
        PanelDaftarObatLayout.setVerticalGroup(
            PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDaftarObatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelDaftarObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBorder1.setBackground(new java.awt.Color(204, 204, 204));
        panelBorder1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 15));
        panelBorder1.setForeground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(925, 229));

        jLabel2.setText(":");

        jLabel3.setText(":");

        jLabel4.setText(":");

        labelAturanPakai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAturanPakai.setText("Aturan Pakai");

        labelPetunjukPenyimpnan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelPetunjukPenyimpnan.setText("Penyimpanan");

        labelHarga.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelHarga.setText("Harga");

        labelStok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelStok.setText("Stok");

        jLabel6.setText(":");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");
        jLabel10.setPreferredSize(new java.awt.Dimension(5, 15));

        obatLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        obatLB.setText("Nama Obat");

        LabelDosis.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LabelDosis.setText("Dosis  ");

        labelKegunaan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelKegunaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKegunaan.setText("Kegunaan  ");

        labelKomposisi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelKomposisi.setText("Komposisi");

        labelNoRegistrasi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelNoRegistrasi.setText("No Registrasi ");

        labelKadaluarsa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelKadaluarsa.setText("Kadaluarsa");

        jLabel5.setText(":");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBorder1Layout.createSequentialGroup()
                                    .addComponent(labelKadaluarsa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panelBorder1Layout.createSequentialGroup()
                                    .addComponent(LabelDosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(20, 20, 20)))
                            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder1Layout.createSequentialGroup()
                            .addComponent(labelAturanPakai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(labelPetunjukPenyimpnan)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelKegunaan)
                    .addComponent(labelKomposisi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosisLB)
                    .addComponent(kegunaanLB)
                    .addComponent(aturanPakaiLB)
                    .addComponent(penyimpananLB)
                    .addComponent(komposisiLB)
                    .addComponent(kadaluarsaLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(obatLB, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(labelHarga)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(hargaLB)
                        .addGap(20, 20, 20)
                        .addComponent(labelStok)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stokLB)
                        .addContainerGap(186, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(labelNoRegistrasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noRegistrasiLB)
                        .addGap(112, 112, 112))))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obatLB)
                    .addComponent(labelNoRegistrasi)
                    .addComponent(jLabel3)
                    .addComponent(noRegistrasiLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDosis)
                    .addComponent(jLabel5)
                    .addComponent(dosisLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKegunaan)
                    .addComponent(jLabel2)
                    .addComponent(kegunaanLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKomposisi)
                    .addComponent(jLabel4)
                    .addComponent(komposisiLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKadaluarsa)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kadaluarsaLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelAturanPakai)
                    .addComponent(aturanPakaiLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPetunjukPenyimpnan)
                    .addComponent(jLabel7)
                    .addComponent(penyimpananLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHarga)
                    .addComponent(jLabel8)
                    .addComponent(labelStok)
                    .addComponent(jLabel9)
                    .addComponent(hargaLB)
                    .addComponent(stokLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDaftarObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDaftarObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked

    }//GEN-LAST:event_editButtonMouseClicked

    private void TableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableObatMouseClicked
        namaObat = TableObat.getModel().getValueAt(TableObat.getSelectedRow(), 0).toString();

//        TableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                if (!e.getValueIsAdjusting()) { // Ensure we don't capture intermediate selection changes
//                    int selectedRow = TableObat.getSelectedRow();
//                    setRowIndex(selectedRow);
//                    setNamaObat(TableObat.getValueAt(selectedRow, 0).toString());
//                    if (selectedRow != -1) {
//                        // If a row is selected, perform your action here
//                        namaObat = TableObat.getValueAt(selectedRow, 0).toString();
//                        
//                        System.out.println(TableObat.getValueAt(selectedRow, 0).toString());
//                        System.out.println("Selected Row Index: " + selectedRow);
//                    }
//                }
//            }
//        }
//        );
    }//GEN-LAST:event_TableObatMouseClicked

//    public void show_table() {
//        try {
//            Database db = new Database();
//            db.connect();
//            String sql = "select * from Obat";
//            ResultSet rs = db.getData(sql);
//            DefaultTableModel table = (DefaultTableModel) TableObat.getModel();
//
//            table.setRowCount(0);
//            while (rs.next()) {
//                Object[] rowData = {rs.getString("nama_obat"), rs.getString("no_registrasi"), rs.getInt("stock"), rs.getInt("harga")};
//                table.addRow(rowData);
//            }
//        } catch (SQLException e) {
//            Logger.getLogger(ManageObatForm.class.getName()).log(Level.SEVERE, null, e);
//        }
//        TableObat.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                int selectedRow = TableObat.getSelectedRow();
//                if (selectedRow != -1) {
//                    String namaObat = (String) TableObat.getValueAt(selectedRow, 0);
//                    tampilkanDetailObat(namaObat);
//                }
//            }
//        });
//    }
    public void setObat(Obat obat) {
        obatLB.setText(obat.getNama_obat());
        dosisLB.setText(obat.getDosis());
        kegunaanLB.setText(obat.getKegunaan());
        komposisiLB.setText(obat.getKomposisi());
        noRegistrasiLB.setText(obat.getNo_registrasi());
        kadaluarsaLB.setText(obat.getKadaluarsa().toString());
        aturanPakaiLB.setText(obat.getAturan_pakai());
        penyimpananLB.setText(obat.getPetunjuk_penyimpanan());
        hargaLB.setText(String.valueOf(obat.getHarga()));
        stokLB.setText(String.valueOf(obat.getStock()));
    }
    
    public void tampilkanDetailObat(String namaObat) {
        try {
            Database db = new Database();
            db.connect();
            String sql = "SELECT * FROM Obat WHERE nama_obat = '" + namaObat + "'";
            ResultSet rs = db.getData(sql);

            if (rs.next()) {
                Obat obat = new Obat(
                        rs.getString("nama_obat"),
                        rs.getString("dosis"),
                        rs.getString("kegunaan"),
                        rs.getString("komposisi"),
                        rs.getString("no_registrasi"),
                        rs.getDate("kadaluarsa"),
                        rs.getString("aturan_pakai"),
                        rs.getString("petunjuk_penyimpanan"),
                        rs.getInt("harga"),
                        rs.getInt("stock")
                );

                setObat(obat);
            } else {
                JOptionPane.showMessageDialog(null, "Data obat tidak ditemukan.");
            }
        } catch (SQLException e) {
            Logger.getLogger(ManageObatForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public Table getTableObat() {
        return TableObat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDosis;
    private GUI.PanelBorder PanelDaftarObat;
    private GUI.PanelBorder PanelSearch;
    private ComponentGUI.Table TableObat;
    private javax.swing.JScrollPane TableScrollPanel;
    private javax.swing.JLabel aturanPakaiLB;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel dosisLB;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel hargaLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel kadaluarsaLB;
    private javax.swing.JLabel kegunaanLB;
    private javax.swing.JLabel komposisiLB;
    private javax.swing.JLabel labelAturanPakai;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelKadaluarsa;
    private javax.swing.JLabel labelKegunaan;
    private javax.swing.JLabel labelKomposisi;
    private javax.swing.JLabel labelNoRegistrasi;
    private javax.swing.JLabel labelPetunjukPenyimpnan;
    private javax.swing.JLabel labelStok;
    private javax.swing.JLabel noRegistrasiLB;
    private javax.swing.JLabel obatLB;
    private GUI.PanelBorder panelBorder1;
    private javax.swing.JLabel penyimpananLB;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel stokLB;
    // End of variables declaration//GEN-END:variables
}
